"use client";
import { Inter } from "next/font/google";
import style from "./page.module.css";
import Nav from "@/components/navbar/nav";
import Contact from "@/components/footer/footer";
import Top from "@/components/navbar/headerTop";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Gangster Clothing",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const router = usePathname();
  const excludedPaths = ["/auth/login", "/auth/signup"];
  const shouldExcludeTopAndContact = excludedPaths.includes(router);

  return (
    <html lang="en">
      <body className={inter.className}>
        {!shouldExcludeTopAndContact && <Top />}
        <div className={style.navbar}>
          {!shouldExcludeTopAndContact && <Nav />}
        </div>
        {children}
        {!shouldExcludeTopAndContact && <Contact />}
      </body>
    </html>
  );
}
