import "./globals.css";
import Nav from "@/components/navbar/nav";
import Top from "@/components/headerTop";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Gangster Clothing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="shortcut icon" href="./logo.png" />
      <body className={inter.className}>
        <Top />
        <Nav />
        {children}
      </body>
    </html>
  );
}
