import "./globals.css";
import { Inter } from "next/font/google";
import Wrapper from "./Wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Gangster Clothing",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  );
}
